const actions = {
  STORE_CURRENT_USER: "STORE_CURRENT_USER",
  STORE_ALL_TRANSACTIONS: "STORE_ALL_TRANSACTIONS",
  DISPLAY_TRANSACTIONS: "DISPLAY_TRANSACTIONS",
  DISPLAY_TOTAL_EXPENSE: "DISPLAY_TOTAL_EXPENSE",
};
export default actions;
